# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2878634e703f7baa694ee1c0a4e57d2"
name = "rod-builder-pro"
handle = "rod-builder-pro-2"
application_url = "https://sitting-interview-thompson-horse.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://sitting-interview-thompson-horse.trycloudflare.com/auth/callback", "https://sitting-interview-thompson-horse.trycloudflare.com/auth/shopify/callback", "https://sitting-interview-thompson-horse.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://sitting-interview-thompson-horse.trycloudflare.com/apps/rbp"
subpath = "rbp"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
